name: Working with CI-CD-Pipelines

on: 
    push:
        branches: 
            main      
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            # Step 1: Checkout the code from GitHub repository
            - name : Checkout code
              uses : actions/checkout@v3

            # Step 2: AWS credentials
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # AWS Access Key from GitHub secrets
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS Secret Key from GitHub secrets
                aws-region: ap-south-1  # Your AWS region
          
            # Step 3: Log in to Amazon ECR using GitHub Secrets
            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            # Step 4: Build the Docker image and push it to Amazon ECR
            - name: Build and Push Docker image
              uses: docker/build-push-action@v3
              with:
                context: .
                file: ./app/Dockerfile
                push: true
                tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-repo-name:latest

            # Step 5: Set up AWS CLI with credentials for deployment
            - name: Set up AWS CLI
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}